## Name of the workflow
name: TechTrends - Package with Docker
## Triggered on every push
on:
  push:
    branches:
      - 'main'
## Steps to execute
jobs:
  ## Name of job
  docker:
    ## Operating system for workflow to run on
    runs-on: ubuntu-latest
    ## Steps
    steps:
      ## Checkout existing code in the repository, login to docker-hub, build and push image
    - 
      name: Checkout
      uses: actions/checkout@v2  
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./techtrends
        platform: linux/amd64
        push: true
        tags: techtrends:latest
